name: backend-in-mem

on:
  push:
    branches:
      - github-action
    paths:
      - 'common/**.hs'
      - 'backend/app/**.hs'
      - 'backend/src/carrier/mem/**.hs'
      - 'test/**.hs'
      - 'cabal.project.backend-in-mem'
      - 'realworld-haskell.cabal'
      - 'Setup.hs'
      - 'nix/**'
      - 'default.nix'
      - '.github/workflows/common.yml'
      - '.github/workflows/backend-in-mem.yml'

jobs:
  backend-in-mem:
    uses: ./.github/workflows/common.yml
    with:
      flag: backend-in-mem
    secrets:
      CACHIX_AUTH_TOKEN: ${{secrets.CACHIX_AUTH_TOKEN}}
