name: backend-in-mem

on:
  push:
    paths:
      - 'common/**.hs'
      - 'backend/app/**.hs'
      - 'backend/src/api/**.hs'
      - 'backend/src/effect/**.hs'
      - 'backend/src/carrier/mem/**.hs'
      - 'test/**.hs'
      - 'cabal.project.backend-in-mem'
      - 'realworld-haskell.cabal'
      - 'Setup.hs'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/nix-build.yml'
      - '.github/workflows/backend-in-mem.yml'

jobs:
  backend-in-mem:
    uses: ./.github/workflows/nix-build.yml
    with:
      exe: in-mem
    secrets:
      CACHIX_AUTH_TOKEN: ${{secrets.CACHIX_AUTH_TOKEN}}
