name: backend

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [ubuntu-20.04, macos-10.15]
        # https://github.com/input-output-hk/haskell.nix/blob/85755332c0698ab90d061c079f3c25710675bb85/docs/reference/supported-ghc-versions.md
        nixpkgsPin: [2111,unstable]
        # NOTE: ghcVersion is determine by nipkgsPin in nix expression, 2111 -> ghc8107, unstable -> ghc921
        # ghcVerson: [ghc8107, ghc921]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v14
      with:
        extra_nix_config: |
          substituters = https://cache.nixos.org https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - uses: cachix/cachix-action@v10
      with:
        name: fanshi1028-realworld-haskell
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community

    - name: nix build
      run: |
        nix-build -j4 --argstr nixpkgsPin ${{matrix.nixpkgsPin}}
