name: backend-rel8

on:
  push:
    paths:
      - 'common/**.hs'
      - 'backend/app/**.hs'
      - 'backend/src/api/**.hs'
      - 'backend/src/effect/**.hs'
      - 'backend/src/carrier/rel8/**.hs'
      - 'test/**.hs'
      - 'cabal.project.backend-rel8'
      - 'realworld-haskell.cabal'
      - 'Setup.hs'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/nix-build.yml'
      - '.github/workflows/backend-rel8.yml'

jobs:
  backend-rel8:
    uses: ./.github/workflows/nix-build.yml
    with:
      exe: rel8
    secrets:
      CACHIX_AUTH_TOKEN: ${{secrets.CACHIX_AUTH_TOKEN}}
