name: backend

on:
  push:
    branches:
      - github-action
    paths:
      - 'common/**.hs'
      - 'backend/**.hs'
      - 'test/**.hs'
      - 'cabal.project'
      - 'realworld-haskell.cabal'
      - 'Setup.hs'
      - 'nix/**'
      - 'default.nix'
      - '.github/workflows/common.yml'
      - '.github/workflows/backend.yml'

jobs:
  backend-build:
    uses: ./.github/workflows/common.yml
    with:
      exe: backend
