name: backend

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache install Nix packages
      uses: rikhuijzer/cache-install@v1.0.8
      with:
        key: key-${{ hashFiles('default.nix') }}-${{ hashFiles('realworld-haskell.cabal') }}
        nix_file: 'default.nix'

    - name: build
      run: nix-build -A realworld-haskell.components.exes.realworld-haskell
