name: backend

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v14
      with:
        extra_nix_config: |
          trusted-substituters = https://cache.nixos.org https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - uses: cachix/cachix-action@v10
      with:
        name: fanshi1028-realworld-haskell
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community

    - name: build-test
      run: |
        nix-build -j4 -o test-result -A realworld-haskell.components.tests.realworld-haskell-test

    - name: run-test
      run: |
        nix-shell -p postgresql_13 --run "./test-result/bin/realworld-haskell-test"

    - name: nix build
      if: ${{ success() }}
      run: |
        nix-build -j4 -o exe-result -A realworld-haskell.components.exes.realworld-haskell
