name: frontend-warp

on:
  push:
    branches:
      - github-action
    paths:
      - 'common/**.hs'
      - 'frontend/app/**.hs'
      - 'frontend/src/js/**.hs'
      - 'test/**.hs'
      - 'cabal.project.frontend-warp'
      - 'realworld-haskell.cabal'
      - 'Setup.hs'
      - 'nix/**'
      - 'default.nix'
      - '.github/workflows/nix-build.yml'
      - '.github/workflows/frontend-warp.yml'

jobs:
  frontend-js:
    uses: ./.github/workflows/nix-build.yml
    with:
      flag: warp
    secrets:
      CACHIX_AUTH_TOKEN: ${{secrets.CACHIX_AUTH_TOKEN}}
