name: frontend-warp

on:
  push:
    paths:
      - 'common/**.hs'
      - 'frontend/app/**.hs'
      - 'frontend/src/api/**.hs'
      - 'frontend/src/js/**.hs'
      - 'test/**.hs'
      - 'cabal.project.frontend-warp'
      - 'realworld-haskell.cabal'
      - 'Setup.hs'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/nix-build.yml'
      - '.github/workflows/frontend-warp.yml'

jobs:
  frontend-js:
    uses: ./.github/workflows/nix-build.yml
    with:
      exe: warp
    secrets:
      CACHIX_AUTH_TOKEN: ${{secrets.CACHIX_AUTH_TOKEN}}
