name: frontend

on:
  push:
    branches:
      - github-action
    paths:
      - 'common/**.hs'
      - 'frontend/**.hs'
      - 'test/**.hs'
      - 'cabal.project'
      - 'realworld-haskell.cabal'
      - 'Setup.hs'
      - 'nix/**'
      - 'default.nix'
      - '.github/workflows/common.yml'
      - '.github/workflows/frontend.yml'

jobs:
  frontend-build:
    uses: ./.github/workflows/common.yml
    with:
       exe: frontend
       matrixFlags:
         - frotend-vty
