name: frontend-js

on:
  push:
    branches:
      - github-action-nix-flake
    paths:
      - 'common/**.hs'
      - 'frontend/app/**.hs'
      - 'frontend/src/api/**.hs'
      - 'frontend/src/js/**.hs'
      - 'test/**.hs'
      - 'cabal.project.frontend-js'
      - 'realworld-haskell.cabal'
      - 'Setup.hs'
      - 'nix/**'
      - 'default.nix'
      - '.github/workflows/nix-build.yml'
      - '.github/workflows/frontend-js.yml'

jobs:
  frontend-js:
    uses: ./.github/workflows/nix-build.yml
    with:
      exe: js
    secrets:
      CACHIX_AUTH_TOKEN: ${{secrets.CACHIX_AUTH_TOKEN}}
