name: nix-build

on:
  workflow_call:
    inputs:
      exe:
        description: part of flag to choose an executable
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        description: cachix token

jobs:
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        ghcVersion: [8107, 922, 923]
        exe: ['${{inputs.exe}}']
        exclude:
          # frontend dependencies not yet work with ghc92x
          - ghcVersion: 922
            exe: js
          - ghcVersion: 923
            exe: js
          - ghcVersion: 922
            exe: vty
          - ghcVersion: 923
            exe: vty
          - ghcVersion: 922
            exe: warp
          - ghcVersion: 923
            exe: warp
          - ghcVersion: 922
            exe: native
          - ghcVersion: 923
            exe: native
          # oom cases
          # # in-mem
          - ghcVersion: 8107
            exe: in-mem
            os: ubuntu-18.04
          - ghcVersion: 8107
            exe: in-mem
            os: ubuntu-20.04
          # # native
          - ghcVersion: 8107
            exe: native
            os: ubuntu-18.04
          - ghcVersion: 8107
            exe: native
            os: ubuntu-20.04
          # # warp
          - ghcVersion: 8107
            exe: warp
            os: ubuntu-18.04
          - ghcVersion: 8107
            exe: warp
            os: ubuntu-20.04

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3.0.2

    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          # access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          substituters = https://cache.nixos.org https://cache.iog.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - uses: cachix/cachix-action@v10
      with:
        name: fanshi1028-realworld-haskell
        authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
        extraPullNames: nix-community

    - name: nix build exe (-O2)
      run: |
        nix build -j4 .#ghc${{matrix.ghcVersion}}.${{matrix.exe}}
